name: Build Android APK with Dynamic Version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Generate Dynamic Version
        id: versioning
        run: |
          VERSION_CODE=$((10000 + $(date +%s) % 100000))
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          VERSION_NAME="1.0.$(date +%Y%m%d)-$SHORT_SHA"
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Inject Version into build.gradle
        run: |
          sed -i "s/versionCode .*/versionCode $VERSION_CODE/" app/build.gradle
          sed -i 's/versionName ".*"/versionName "'"$VERSION_NAME"'"/' app/build.gradle

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-${{ env.VERSION_NAME }}.apk
          path: app/build/outputs/apk/release/app-release.apk
